### ISSUE TITLE
Bad values for PWR_MGT_2 ?

### ISSUE THREAD

**Issue by lgm42** [simondlevy/MPU#4]
https://github.com/simondlevy/MPU/blob/c79fcbb8a81cea495ee825ea7763ffda17e172e5/src/MPU.cpp#L143

I think you've made a mistake with the initialization of this register.
The value INV_CLK_INTERNAL should be only for the register PWR_MGMT_1 of the MPU9250 (I don't know for the PMU6000)
The PWR_MGMT_2 is used only to activate / deactivate sensors

![image](https://user-images.githubusercontent.com/6039130/44838791-6575c680-ac3d-11e8-95ff-c25f2457bb4e.png)

**Comment by simondlevy** [comment]
Thanks, you're right.  I fixed the error.
