### ISSUE TITLE
MPU9250 reset problem

### ISSUE THREAD

**Issue by dschnabel** [simondlevy/MPU#7]
The MPU9250 (in master mode) should disable the internal I2C bus before doing a reset or otherwise we risk a bad state (e.g. no more response from AK8963). See comment [here](https://community.emlid.com/t/solved-ak8963-bad-device-id-error-during-ardupilot-start/267/70).

My suggested fix is to modify [MPU9250::reset()](https://github.com/simondlevy/MPU/blob/master/src/MPU9250.cpp#L146) like so:
```
void MPU9250::reset()
{
    if (!_passthru) {
    	writeMPURegister(USER_CTRL, 0); // disable internal I2C bus
    }

    // reset device
    writeMPURegister(PWR_MGMT_1, 0x80); // Set bit 7 to reset MPU9250

    if (!_passthru) {
    	writeMPURegister(USER_CTRL, I2C_MST_EN); // re-enable internal I2C bus
    }
    delay(100); // Wait for all registers to reset 
}
```
Tested and working for me.

**Comment by simondlevy** [comment]
Thank you, Daniel.  Would you like to do a pull request, so that you will be added to the list of contributors?

**Comment by dschnabel** [comment]
fix is merged, closing.
